import { Cpu, Paperclip } from 'lucide-react'
import { Panel } from '../Primitives'
import { Item, TypeBadge } from '../input/parts'
import { IMPORT_LABEL, fmt } from '../../data/constants'

/** Stage 1: the input exactly as the operator committed it. */
export function InputSummary({ commit, run }) {
  const r = commit.resolved
  const mode = commit.source?.mode
  return (
    <Panel title="What was submitted" icon={Cpu} meta={<span className="num">{commit.id} · {fmt.datetime(commit.created_at)}</span>}>
      <dl className="grid gap-x-8 gap-y-4 sm:grid-cols-2 xl:grid-cols-4">
        <Item label="Client">
          <span className="font-medium">{r.client?.name}</span>
          <span className="block text-[12px] text-slate-500">{r.group?.name ?? 'no group'}</span>
        </Item>
        <Item label="Device">
          {r.device?.device_label}
          <span className="num block text-[12px] text-slate-500">{r.device?.euicc_id}</span>
        </Item>
        <Item label="eSIM identity" mono>
          {r.device?.iccid}
          <span className="block text-[12px] text-slate-500">{r.device?.profile_name}</span>
        </Item>
        <Item label="RSP environment">
          {r.rsp_environment?.name}
          <span className="num block text-[12px] text-slate-500">{r.rsp_environment?.smdp_endpoint}</span>
        </Item>
        <Item label="Network and authentication">
          {r.network?.name}
          <span className="block text-[12px] text-slate-500">
            {r.network?.auth?.method} · PLMN {r.network?.plmn}
          </span>
        </Item>
        <Item label="Data source">
          <TypeBadge typeKey={mode} label={commit.source?.type} />
        </Item>
        <Item
          label={
            { realtime: 'Stream', upload: 'Your file', scenario: 'Scenario' }[mode] ?? 'Dataset'
          }
          mono={mode !== 'scenario'}
        >
          {mode === 'realtime'
            ? 'Live grid feed'
            : mode === 'scenario'
              // A built-in scenario has no file on disk: name it instead of
              // leaving the row empty.
              ? r.dataset?.title ?? r.dataset?.id ?? 'Built-in scenario'
              : run?.dataset_path}
        </Item>
        <Item label="Operator files">
          <span className="flex items-center gap-1.5">
            <Paperclip size={13} className="text-slate-500" aria-hidden />
            {commit.attachments?.length ?? 0} attached
          </span>
        </Item>
      </dl>
      {mode === 'scenario' && (
        <p className="mt-4 text-[12px] leading-relaxed text-policy">
          A built-in scenario from Run self-healing: synthetic telemetry generated for this run, on a device from the
          client registry. Nothing here describes a real customer, device or network.
        </p>
      )}
      {mode === 'synthetic' && commit.source?.type !== IMPORT_LABEL && (
        <p className="mt-4 text-[12px] leading-relaxed text-policy">
          Synthetic / simulated data. Nothing here describes a real customer, device or network.
        </p>
      )}
      {commit.source?.type === IMPORT_LABEL && (
        <p className="mt-4 text-[12px] leading-relaxed text-hold">
          An imported dataset: supplied by the operator and checked for format only, not generated by this project.
        </p>
      )}
      {mode === 'upload' && (
        <p className="mt-4 text-[12px] leading-relaxed text-hold">
          Supplied by the operator and checked for format only. The detector and agent ran on it as given; what the
          device does in response comes from the simulated RSP server
          {r.dataset?.has_fault_labels ? '.' : ', which was not told about a fault because the file has no fault labels, so a fix cannot show as recovered.'}
        </p>
      )}
    </Panel>
  )
}

/** Stage 2: what the agent loop did with it. */
export function ProcessingSummary({ run, incidents = [] }) {
  const live = run.mode === 'realtime'
  return (
    <dl className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <Tile label={live ? 'Samples so far' : 'Samples processed'} value={run.samples} />
      <Tile label={live ? 'Feed' : 'Loop time'} value={live ? (run.feed_running ? 'Running' : 'Stopped') : fmtMs(run.wall_ms)}
        hint={live ? (run.started_feed ? 'Started by Process data' : 'Already running') : 'MONITOR through LEARN'} />
      <Tile label="Incidents opened" value={incidents.length} hint={incidents.length ? 'by the change-point detector' : 'the detector stayed quiet'} />
      <Tile label="False alarms" value={run.false_positives} hint={live ? 'unknown in live mode' : 'incidents opened on healthy samples'} />
    </dl>
  )
}

function Tile({ label, value, hint }) {
  return (
    <div className="glass-quiet px-3.5 py-3">
      <dt className="label">{label}</dt>
      <dd className="num mt-1 text-xl font-semibold text-slate-100">{value}</dd>
      {hint && <p className="mt-1 text-[11px] text-slate-500">{hint}</p>}
    </div>
  )
}

const fmtMs = (v) => (v === null || v === undefined ? '—' : v >= 1000 ? `${(v / 1000).toFixed(2)} s` : `${v.toFixed(0)} ms`)
